<?php

namespace ActeurBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * InscriptionAttenteRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class InscriptionAttenteRepository extends EntityRepository
{
    public function VerifieCode($code){
        $sqb = $this->createQueryBuilder('a');
        $sqb
            ->select('a')
            ->where('a.codeInscription =:code')
            ->andWhere('a.utilise = false')
            ->setParameter('code',$code);
        // $qb->getQuery()->getOneOrNullResult(Query::HYDRATE_SINGLE_SCALAR);
        return $sqb->getQuery()->getScalarResult(Query::HYDRATE_SINGLE_SCALAR);

    }
}
