<?php

namespace AdminBundle\Repository;

/**
 * ProjetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsRepository extends \Doctrine\ORM\EntityRepository
{
    public function projetsValides($limite,$etat){
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.porteur','t')
          //  ->innerJoin('p.media','m')
            ->where('p.selectionne = true')
            ->andWhere('p.etat = :etat')
            ->setParameter('etat',$etat)
            ->orderBy('p.id','DESC')
            ->setMaxResults($limite);
           return $qb->getQuery()
            ->getResult();
    }

    public function tousLesProjetsValides(){
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.porteur','t')
            //  ->innerJoin('p.media','m')
            ->where('p.selectionne = true')
            ->andWhere("p.etat = 'enFinancement'")
            ->orderBy('p.id','DESC');

        return $qb->getQuery()
            ->getResult();
    }
    public function projetsEnFinancement(){
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.porteur','t')
            //  ->innerJoin('p.media','m')
            ->where('p.selectionne = true')
            ->andWhere('DATE_DIFF(p.dateLimite, CURRENT_DATE()) < 0')
            ->orderBy('p.id','DESC');

        return $qb->getQuery()
            ->getResult();
    }
    public function projetsFinancementBoucle(){
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.porteur','t')
            //  ->innerJoin('p.media','m')
            ->where('p.selectionne = true')
            ->andWhere('DATE_DIFF(p.dateLimite, CURRENT_DATE()) < 0')
            ->orderBy('p.id','DESC');

        return $qb->getQuery()
            ->getResult();
    }

    public function projetsRealise(){
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.porteur','t')
            //  ->innerJoin('p.media','m')
            ->where('p.selectionne = true')
            ->andWhere('DATE_DIFF(p.dateLimite, CURRENT_DATE()) < 0')
            ->orderBy('p.id','DESC');

        return $qb->getQuery()
            ->getResult();
    }
}
